services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: moatoon
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: alsdntjdghks123!!
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - moa-network
    restart: always

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    networks:
      - moa-network
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 880:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - moa-network
    restart: always
  
  jenkins:  
    container_name: jenkins
    image: jenkins/jenkins:lts    
    user: root
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - moa-network
    ports:
      - 9090:8080
    privileged: true

networks:
  moa-network:
    driver: bridge