server:
  port: 8080
  ssl:
    enabled: false

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    default: local

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL}
    password: ${SMTP_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

  jwt:
    secret: ${JWT_KEY}
    token:
      access-expiration-time: 7200000    # 2시간
      refresh-expiration-time: 604800000   # 7일

  cloud:
    aws:
      credentials:
        accessKey: ${S3_ACCESS}
        secretKey: ${S3_SECRET}
      region:
        static: ${S3_REGION}
      s3:
        bucket: ${S3_BUCKET}

openvidu:
  url: ${OPENVIDU_URL}
  secret: ${OPENVIDU_SECRET}

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/moa?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        globally_quoted_identifiers: true
        highlight_sql: true
        format_sql: true
        show-sql: false

  data:
    redis:
      host: localhost
      port: 6379

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true

  flyway:
    enabled: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://mysql:3306/moatoon?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        timezone:
          default_storage: NORMALIZE
        globally_quoted_identifiers: true
        highlight_sql: false
        format_sql: false
        show-sql: false

  data:
    redis:
      host: redis
      port: 6379

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: false

  flyway:
    enabled: true

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:~/MoaApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: never

  flyway:
    enabled: false

  data:
    redis:
      host: localhost
      port: 6379
